server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index ntp/index.html;

    location / {
        try_files $uri $uri/ /ntp/index.html;
    }

    location /ntp/ {
        alias /var/www/html/ntp/;
        add_header Cache-Control 'no-store';
    }
}
